"use client";

import { useState } from "react";
import { Noto_Sans_TC } from "@next/font/google";
import { Header, SideMenu } from "@components/Layout";
import styled from "@components/Layout/layout.module.scss";
import "./global.scss";

const notoSansTC = Noto_Sans_TC({
  weight: "400",
  subsets: ["chinese-traditional"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-TW">
      <head className={notoSansTC.className}>
        <title>運營管理系統</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className={styled.layout}>
          <Header />
          <div className={styled.center}>
            <SideMenu />
            <main className={styled.main}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
